import React, { useState } from "react";

import { Loader, FormField, Card } from "../components";

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);

  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-[32px] text-[#222328]">
          The Community ShowCase
        </h1>
        <p className="mt-2 max-w-[500px] text-[#666e75] text-[16px]">
          Browse through a collection of imaginative and visually stunning
          images generated by Mid Journey 2.0 AI.
        </p>
      </div>

      <div className="mt-16">
        <FormField />
      </div>

      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <></>
        )}
      </div>
    </section>
  );
};

export default Home;
